name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
    steps:
    - uses: actions/checkout@v2
      env:
        # use mongodb for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        MONGODB_ENDPOINT: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
